allow matlab for OSX using ifort

diff --git a/bin/select_arch b/bin/select_arch
--- a/bin/select_arch
+++ b/bin/select_arch
@@ -413,9 +413,9 @@ if (( $MATLAB_REQUIRED )); then
          "6")
               CORRECT_MATLAB="true"
               if [[ ${OS} == "osx" ]]; then
-                MATLABGCC="gcc-4.3"
-                MATLABGCXX="g++-4.3"
-                MATLABGFORTRAN="gfortran-4.3"
+                MATLABGCC="icc"
+                MATLABGCXX="icc"
+                MATLABGFORTRAN="ifort"
               else
                 MATLABGCC="gcc-8"
                 MATLABGCXX="g++-8"
@@ -429,8 +429,8 @@ if (( $MATLAB_REQUIRED )); then
   done
 else
   if [[ ${OS} == "osx" ]]; then
-    MATLABGCC="gcc-4.3"
-    MATLABGFORTRAN="gfortran-4.3"
+    MATLABGCC="icc"
+    MATLABGFORTRAN="ifort"
   else
     MATLABGCC="gcc-8"
     MATLABGFORTRAN="gfortran-8"
@@ -438,20 +438,38 @@ else
 fi
 
 if (( $MATLAB_REQUIRED )); then
-  COMP=( `$LS $ARCH/compiler.${MCH}.${OS}.gfo 2>/dev/null` )
-  NUMBER=${#COMP[@]}
-  if (( $NUMBER )) ; then
-    type -P $MATLABGFORTRAN &>/dev/null || \
-     { printf " Warning: you need to install $MATLABGFORTRAN to allow\n for Matlab and CUTEst interaction. Aborting\n" >&2; exit 3; }
-    echo " GNU $MATLABGFORTRAN compiler will be used for Matlab compatibility"
-    COMPILER="compiler.${MCH}.${OS}.gfo"
-    CMP="gfo"
-    COMPUSED=`$LS $ARCH/compiler.${MCH}.${OS}.gfo 2>/dev/null`
-  else
-    error " GNU $MATLABGFORTRAN/$MATLABGCC compilers required for
+  if [[ ${OS} == "osx" ]]; then
+    COMP=( `$LS $ARCH/compiler.${MCH}.${OS}.ifr 2>/dev/null` )
+    NUMBER=${#COMP[@]}
+    if (( $NUMBER )) ; then
+      type -P $MATLABGFORTRAN &>/dev/null || \
+       { printf " Warning: you need to install $MATLABGFORTRAN to allow\n for Matlab and CUTEst interaction. Aborting\n" >&2; exit 3; }
+      echo " Intel $MATLABGFORTRAN compiler will be used for Matlab compatibility"
+      COMPILER="compiler.${MCH}.${OS}.ifr"
+      CMP="ifr"
+      COMPUSED=`$LS $ARCH/compiler.${MCH}.${OS}.ifr 2>/dev/null`
+    else
+      error " GNU $MATLABGFORTRAN/$MATLABGCC compilers required for
  Matlab compatibility not available.
  Installation abandoned"
-    exit 999
+      exit 999
+    fi
+  else
+    COMP=( `$LS $ARCH/compiler.${MCH}.${OS}.gfo 2>/dev/null` )
+    NUMBER=${#COMP[@]}
+    if (( $NUMBER )) ; then
+      type -P $MATLABGFORTRAN &>/dev/null || \
+       { printf " Warning: you need to install $MATLABGFORTRAN to allow\n for Matlab and CUTEst interaction. Aborting\n" >&2; exit 3; }
+      echo " GNU $MATLABGFORTRAN compiler will be used for Matlab compatibility"
+      COMPILER="compiler.${MCH}.${OS}.gfo"
+      CMP="gfo"
+      COMPUSED=`$LS $ARCH/compiler.${MCH}.${OS}.gfo 2>/dev/null`
+    else
+      error " GNU $MATLABGFORTRAN/$MATLABGCC compilers required for
+ Matlab compatibility not available.
+ Installation abandoned"
+      exit 999
+    fi
   fi
 else
   echo -e ' Select fortran compiler\n'
@@ -521,23 +539,46 @@ fi
 if (( $AMPL_REQUIRED )) || (( $MATLAB_REQUIRED )) || \
    (( $CUTEST_REQUIRED )) || (( $SSIDS_REQUIRED )); then
   if (( $MATLAB_REQUIRED )); then
-    CCOMP=( `$LS $ARCH/ccompiler.${MCH}.${OS}.gcc 2>/dev/null` )
-    NUMBER=${#CCOMP[@]}
-    if (( $NUMBER )) ; then
-      type -P $MATLABGCC &>/dev/null || \
-       { echo " Warning: you need to install $MATLABGCC" \
-         echo "to allow for Matlab and CUTEst interaction. Aborting " \
-         >&2; exit 3; }
-      echo " GNU $MATLABGCC compiler will be used for Matlab compatibility"
-      CCOMPILER="ccompiler.${MCH}.${OS}.gcc"
-      #CMP="gcc"
-      CCOMPUSED=`$LS $ARCH/ccompiler.${MCH}.${OS}.gcc 2>/dev/null`
-#     SSIDS="ssids_dum"
-    else
-      error " GNU $MATLABGFORTRAN/$MATLABGCC compilers required for
+    if [[ ${OS} == "osx" ]]; then
+      CCOMP=( `$LS $ARCH/ccompiler.${MCH}.${OS}.icc 2>/dev/null` )
+      NUMBER=${#CCOMP[@]}
+      if (( $NUMBER )) ; then
+        type -P $MATLABGCC &>/dev/null || \
+         { echo " Warning: you need to install $MATLABGCC" \
+           echo "to allow for Matlab and CUTEst interaction. Aborting " \
+           >&2; exit 3; }
+        echo " Intel $MATLABGCC compiler will be used for Matlab compatibility"
+        CCOMPILER="ccompiler.${MCH}.${OS}.icc"
+        #CMP="icc"
+        CCOMPUSED=`$LS $ARCH/ccompiler.${MCH}.${OS}.icc 2>/dev/null`
+        SSIDS="ssids_dum"
+      else
+        error " GNU $MATLABGFORTRAN/$MATLABGCC compilers required for
  Matlab compatibility not available.
  Installation abandoned"
-      exit 999
+        exit 999
+      fi
+    else
+      CCOMP=( `$LS $ARCH/ccompiler.${MCH}.${OS}.gcc 2>/dev/null` )
+      NUMBER=${#CCOMP[@]}
+      if (( $NUMBER )) ; then
+        type -P $MATLABGCC &>/dev/null || \
+         { echo " Warning: you need to install $MATLABGCC" \
+           echo "to allow for Matlab and CUTEst interaction. Aborting " \
+           >&2; exit 3; }
+        echo " GNU $MATLABGCC compiler will be used for Matlab compatibility"
+        CCOMPILER="ccompiler.${MCH}.${OS}.gcc"
+        #CMP="gcc"
+        CCOMPUSED=`$LS $ARCH/ccompiler.${MCH}.${OS}.gcc 2>/dev/null`
+        if [[ ${OS} == "osx" ]]; then
+          SSIDS="ssids_dum"
+        fi
+      else
+        error " GNU $MATLABGFORTRAN/$MATLABGCC compilers required for
+ Matlab compatibility not available.
+ Installation abandoned"
+        exit 999
+      fi
     fi
   else
     echo -e ' Select C compiler\n'
